### ISSUE TITLE
what  convert  s  model-00001.x.safetensors  to pytorch_model.bin, tf_model.h5, model.ckpt.index

### ISSUE THREAD

**Issue by wavelet2008** [tosiyuki/LLaVA-JP#1]
$ sh  scripts/finetune_llm_jp_1.3b_bf.sh 
llm-jp/llm-jp-1.3b-v1.0

SError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory llm-jp/llm-jp-1.3b-v1.0.
ubuntu@ubuntu-X10SRA:~/mml/LLaVAjp$ ls  -lt llm-jp/llm-jp-1.3b-v1.0/
 
-rw-rw-r-- 1 ubuntu ubuntu 4997886200 1月  17 14:46 model-00001-of-00002.safetensors
-rw-rw-r-- 1 ubuntu ubuntu       4551 1月  17 14:34 README.md
-rw-rw-r-- 1 ubuntu ubuntu       1519 1月  17 14:34 gitattributes
-rw-rw-r-- 1 ubuntu ubuntu       1916 1月  17 14:34 tokenizer_config.json
-rw-rw-r-- 1 ubuntu ubuntu    3243009 1月  17 14:34 tokenizer.json
-rw-rw-r-- 1 ubuntu ubuntu       1200 1月  17 14:34 config.json
-rw-rw-r-- 1 ubuntu ubuntu        276 1月  17 14:34 special_tokens_map.json
-rw-rw-r-- 1 ubuntu ubuntu      71079 1月  17 14:34 model.safetensors.index.json
-rw-rw-r-- 1 ubuntu ubuntu 1316062920 1月  17 14:29 model-00002-of-00002.safetensors
loading files from website 
https://huggingface.co/toshi456/llava-jp-1.3b-v1.0/tree/main     

what shoud i do convert  s  model-00001.x.safetensors  to pytorch_model.bin, tf_model.h5, model.ckpt.index

**Comment by tosiyuki** [comment]
Can you tell me what version of hugigface you are using?

**Comment by wavelet2008** [comment]
Translation: Thank you for your prompt reply, my version is 4.28.0


if __name__ == "__main__":
    parser = transformers.HfArgumentParser(
        (ModelArguments, DataArguments, TrainingArguments))
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
    model_path = 'toshi456/llava-jp-1.3b-v1.0'
    model_path = 'toshi456/llm-jp-1.3b-v1.0'
    #model_args.vision_tower = "openai/clip-vit-large-patch14-336"
    model_args.vision_tower = "toshi456/clip-vit-large-patch14-336"
    device = "cuda" if torch.cuda.is_available() else "cpu"
    torch_dtype = torch.bfloat16 if device=="cuda" else torch.float32
    torch_dtype = torch.float32 if device=="cuda" else torch.float32

    model = LlavaGpt2ForCausalLM.from_pretrained(
        model_path,
        low_cpu_mem_usage=True,
        use_safetensors=True,
        torch_dtype=torch_dtype,
        device_map='auto',
    )


home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/modeling_utils.py: │
│ 458 in load_state_dict                                                                           │
│                                                                                                  │
│    455 │   │   │   │   │   │   "model. Make sure you have saved the model properly."             │
│    456 │   │   │   │   │   ) from e                                                              │
│    457 │   │   except (UnicodeDecodeError, ValueError):                                          │
│ ❱  458 │   │   │   raise OSError(                                                                │
│    459 │   │   │   │   f"Unable to load weights from pytorch checkpoint file for '{checkpoint_f  │
│    460 │   │   │   │   f"at '{checkpoint_file}'. "                                               │
│    461 │   │   │   │   "If you tried to load a PyTorch model from a TF 2.0 checkpoint, please s  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: Unable to load weights from pytorch checkpoint file for 'toshi456/llm-jp-1.3b-v1.0/model-00001-of-00002.safetensors' at 
'toshi456/llm-jp-1.3b-v1.0/model-00001-of-00002.safetensors'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
(minigpt4) ubuntu@ubuntu-X10SRA:~/mml/LLaVAjp$ pip show transformers 
Name: transformers
Version: 4.28.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, tokenizers, tqdm
Required-by: peft, sentence-transformers

**Comment by wavelet2008** [comment]
> Can you tell me what version of hugigface you are using?

(minigpt4) ubuntu@ubuntu-X10SRA:~/mml/LLaVAjp$ python  demo_llava.py 
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
toshi456/llm-jp-1.3b-v1.0
Traceback (most recent call last):
  File "/home/ubuntu/mml/LLaVAjp/demo_llava.py", line 34, in <module>
    tokenizer = transformers.AutoTokenizer.from_pretrained(
  File "/home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 702, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1841, in from_pretrained
    return cls._from_pretrained(
  File "/home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2004, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum PyDecoderWrapper at line 177 column 3
(minigpt4) ubuntu@ubuntu-X10SRA:~/mml/LLaVAjp$ pip show transformers
Name: transformers
Version: 4.31.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: llava, peft, sentence-transformers

**Comment by wavelet2008** [comment]
minigpt4) ubuntu@ubuntu-X10SRA:~/mml/LLaVAjp$ python  demo_llava.py 
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.07it/s]
toshi456/llm-jp-1.3b-v1.0
Traceback (most recent call last):
  File "/home/ubuntu/mml/LLaVAjp/demo_llava.py", line 34, in <module>
    tokenizer = transformers.AutoTokenizer.from_pretrained(
  File "/home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 702, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1841, in from_pretrained
    return cls._from_pretrained(
  File "/home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2004, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/ubuntu/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum PyDecoderWrapper at line 177 column 3

**Comment by tosiyuki** [comment]
Sorry, I cannot reproduce the error in my environment.Could you please tell me more about your environment? About library and os and python version.
